### PR TITLE
Updates following the minor revision of the paper

### PR DESCRIPTION
**Pull request by nperraud**
This includes 
* 2 new 2D ConvNet architectures (one is not entirely working properly),
* the speed test,
* new results.

What is not included is a notebook to test the 2D ConvNet architecture. Should I include it? I would need to clean it before.

### CODE REVIEW

**Comment by mdeff** [comment]
Thanks!

What is the notebook testing? If it's worthwhile to share it I would include it. It might even serve us in the future. ;)

Should we keep the 2D ConvNet architecture that doesn't really work?

**Comment by nperraud** [comment]
Could we make a folder for the stuff we want to keep but that are not in a very good shape. We could put the notebook and the cnn.py in this folder. Beside the bug, the CNN implementation is  better than the one I eventually used. So I think we should keep it in case I figure out why batch norm is not working one day.

**Comment by mdeff** [comment]
Good idea! We could have something like `staging` or `experimental`.

**Comment by nperraud** [comment]
Good let us go for experimental

**Comment by mdeff** [comment]
Please also state in the README what `experimental` is.

**Comment by nperraud** [comment]
It should be ready for merging...

**Comment by mdeff** [comment]
LGTM! Thanks @nperraud

**Pull request merged**
